-- ==========================================
-- IT Help Desk - Database Schema & Migrations
-- ==========================================

-- 1. Create Categories Table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Profiles Table (Extended user data)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Tickets Table
CREATE TABLE public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    user_email TEXT,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    priority TEXT DEFAULT 'low',
    status TEXT DEFAULT 'open',
    attachment_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create Comments Table (For future use & assignment requirements)
CREATE TABLE public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT REFERENCES public.tickets(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- Security: Row Level Security (RLS) Policies
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Tickets Policies
CREATE POLICY "Logged in users can select" 
ON public.tickets FOR SELECT USING (auth.uid() IS NOT NULL);

CREATE POLICY "Users can insert their own tickets" 
ON public.tickets FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Logged in users can update" 
ON public.tickets FOR UPDATE USING (auth.uid() IS NOT NULL);

-- Categories Policies
CREATE POLICY "Everyone can read categories" 
ON public.categories FOR SELECT USING (true);

-- ==========================================
-- Seed Data: Insert Default Categories
-- ==========================================
INSERT INTO public.categories (name) VALUES 
('Хардуер'), 
('Софтуер'), 
('Мрежа и Интернет'), 
('Друго')
ON CONFLICT DO NOTHING;